### ISSUE TITLE
native app

### ISSUE THREAD

**Issue by AntonioGHub** [euangoddard/clipboard2markdown#11]
Have you ever thought of wrapping turndown into a cross platform desktop native app?

You may have your clipboard monitored and the paste-to-markdown feature triggered by, for instance, a hotkey.
Maybe it would not be extremely expensive to wrap turndown using [React Native](https://facebook.github.io/react-native/).

This would be definitively great!, and by the way, it would also make happy those who, like me, wish a turndown browser extension existed.

**Comment by euangoddard** [comment]
It is not something I had thought of for the project, but it may well be helpful for people. I guess something like Electron would solve this issue without the need for React Native or similar. If you'd like to do this then I think a separate project which uses this library would be the best solution for this. If you need any changes in this library to improve interoperability, please re-open this issue - I will close it for the moment as I'm not sure there is anything to be done.

**Comment by AntonioGHub** [comment]
I don't think I will be implementing it, at least in the medium-short term I surely would not get around to it, but thank you for your willingness to help and for the advice about Electron.
