### ISSUE TITLE
hi !! there is no way to comment... so i made an issue

### ISSUE THREAD

**Issue by aahnik** [euangoddard/clipboard2markdown#13]
### LOVE U ... Thanks for this tool.. 
# it saved my day
_thanks a lot again...
Close this issue as soon as you have read it @euangoddard @LuRsT @omgmog @epsil @FaithPatrick_ 
# 👍

**Comment by euangoddard** [comment]
Hey @aahnik. Glad this helped you out. Really appreciate you getting in touch like this 😄

**Comment by LuRsT** [comment]
This comment made my day (even if I didn't really do much work on this project, I love seeing humans being good), thanks for this @aahnik!

**Comment by FaithPatrick** [comment]
I'm glad to hear it helps though I didn't do much on this project. :-)

**Comment by edsaperia** [comment]
I want to thank you as well, I use this tool several times a week 🏆

**Comment by euangoddard** [comment]
@edsaperia thanks for letting me know. It's great to hear people are getting benefit from the project after so many years 😊
