### ISSUE TITLE
Doesn't work on Firefox 88 (Ubuntu 20.04 and Windows 10)

### ISSUE THREAD

**Issue by lamyergeier** [euangoddard/clipboard2markdown#14]
Hi! It doesn't work on the latest Firefox 82. When we paste into the website, the website becomes blank. Although it works fine on the latest Chrome.

Could you please have a look?

**Comment by euangoddard** [comment]
Hi, I've just updated my Firefox to 82 and it seems to work fine for me. I am on MacOS Catalina so I'm not sure if that makes any difference. Are there any errors in the console after pasting?

**Comment by anishmittal2020** [comment]
As can be seen the website becomes blank and only the watermark is visible in the background after pasting in  firefox. Following are the errors:

![Screenshot from 2020-11-13 10-52-05](https://user-images.githubusercontent.com/42092626/99059086-5c633c80-259e-11eb-8158-704a2d0cc31f.png)

**Comment by euangoddard** [comment]
I don't think any of those messages are critical to the functionality. Can you try with different clipboard content- maybe something really simple. If that is still not working then it's nothing to do with the value you're pasting

**Comment by anishmittal2020** [comment]
@euangoddard  I pasted very simple: [euangoddard](https://github.com/euangoddard) / **[clipboard2markdown](https://github.com/euangoddard/clipboard2markdown)**

Pasted this from the top of this page!

**Comment by euangoddard** [comment]
It's tricky for me to help much here as I don't have access to an Ubuntu machine. If I had to guess it's something to do with how the clipboard works differently on the different OSs. The generation is a bit of a hack as it hijacks the native paste into a hidden text area and uses the value of that textarea to process into markdown so it could be some subtle timing issue

**Comment by anishmittal2020** [comment]
But on the same machine it works fine on Google Chrome.

**Comment by euangoddard** [comment]
Who knows how browser maintainers implement the clipboard interface 😄 . The problem is that unless there is an error I can investigate or I have access to an Ubuntu machine with Firefox 82 on I'm not really what what I can do. Very open to suggestions

**Comment by Massedil** [comment]
I also have this problem since a long time.

With Firefox 88 on a Ubuntu 20.04 computer, it doesn't work.

On another Windows computer : 
- it works with Firefox stable
- it doesn't work with Firefox nightly

How can I help you ?

**Comment by irvnriir** [comment]
same with 88 on Windows

**Comment by euangoddard** [comment]
I've just re-checked on my Mac and this works fine so it looks like it must be to do with how windows deals with the clipboard. Not having a windows machine makes it hard for me to test this. It could be a permissions issue in Firefox for Windows or it could be to do with key-bindings on the event. If anyone can show me an error I can investigate it.

**Comment by Massedil** [comment]
Is it possible for you to add in the JavaScript console some logs with different numbers to debug and see where in the code exactly the JavaScript stops working and maybe point to a function that fails ? Because for now, I can't see any error in the console.  I am available to help !

**Comment by irvnriir** [comment]
The only output is on load of the page

![Screenshot](https://user-images.githubusercontent.com/13949704/120481925-25b90c00-c3a0-11eb-83b1-0b5d1d5ea289.png)

**Comment by euangoddard** [comment]
I suspect it's not something that would error, but rather one of the expected events (e.g. the paste one) won't get triggered due to some security context that is only present on certain OS

**Comment by Massedil** [comment]
I have investigated.

In my Firefox for Ubuntu (88.0.1), this "paste" event is never called : 

https://github.com/euangoddard/clipboard2markdown/blob/2d46aadd373f8b5cdb5fa0763090135ac31def13/clipboard2markdown.js#L174

But this function is correctly called : 

https://github.com/euangoddard/clipboard2markdown/blob/2d46aadd373f8b5cdb5fa0763090135ac31def13/clipboard2markdown.js#L163-L172

I can get the code to works correctly (obviously only with the `CTRL` + `V` keyboard event) by updating the previous function with the content of the first one : 
 
```Javascript
document.addEventListener('keydown', function (event) {
  if (event.ctrlKey || event.metaKey) {
	if (String.fromCharCode(event.which).toLowerCase() === 'v') {
		
	  pastebin.innerHTML = '';
	  pastebin.focus();
	  info.classList.add('hidden');
	  wrapper.classList.add('hidden');
	  
	  // EDIT
	  setTimeout(function () {
	      var html = pastebin.innerHTML;
	      var markdown = convert(html);
	      output.value = markdown;
	      wrapper.classList.remove('hidden');
	      output.focus();
	      output.select();
	  }, 200);
	  // END EDIT
	  
	}
  }
});
```

I hope it helps !

**Comment by irvnriir** [comment]
disabling a security measure in firefox about:config `dom.event.clipboardevents.enabled`, fixes this, but its not something that can/should be a requirement .

**Comment by irvnriir** [comment]
(when its false, pasting functions work fine, except only some sites)

**Comment by Massedil** [comment]
> Disabling the privacy measure in firefox about:config -- dom.event.clipboardevents.enabled = false, fixes this

Thanks !

https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/Preference_reference/dom.event.clipboardevents.enabled

 For me : 
- `dom.event.clipboardevents.enabled = true` : clipboard2markdown works (it solves the problem)
- `dom.event.clipboardevents.enabled = false` : clipboard2markdown does not works

And it explains why the `addEventListener('paste', function ()` is not called.

**Comment by euangoddard** [comment]
So what do people think the resolution should be here? The `paste` specific behaviour seems to be Firefox-related and clearly asking people to change their settings doesn't make sense, but it does seem that it can also be solved by @irvnriir's code change? If the code-change will fix this for everyone then I guess a PR with this change in would be good

**Comment by irvnriir** [comment]
code change ? `dom.event.clipboardevents.enabled` is a user setting .

**Comment by anishmittal2020** [comment]
@euangoddard @Massedil Could you please update so that it works in Firefox?

**Comment by euangoddard** [comment]
@anishmittal2020 feel free to drop a PR in that fixes this and I'll take a look

**Comment by jnm** [comment]
http://euangoddard.github.io/clipboard2markdown/ works fine for me with Firefox 101.0.1 on Ubuntu 20.04. Can this issue be closed?

**Comment by euangoddard** [comment]
Sounds good to me
