### ISSUE TITLE
Chrome extensions

### ISSUE THREAD

**Issue by Agarwal-Nikhil** [euangoddard/clipboard2markdown#6]
Hi! this is a great project. It would be great if we could have a **Chrome extension** that could directly copy the **Markdown-conversion** of the selected text on the webpage. I don't have much experience with web design, but do you think its an easy task?

**Comment by euangoddard** [comment]
I think it should be straight-forward to do if you know how to build Chrome extensions. I also don't have any experience working with them. Would be happy to accept any PRs for one

**Comment by greatghoul** [comment]
https://github.com/webextension-toolbox/generator-web-extension

@euangoddard It's easy to start, just html, javascript and css.

**Comment by euangoddard** [comment]
I'm sure it can be done. I don't really have any time to look into this. I did this project to help out some colleagues a few years ago and don't really maintain it. Always happy to consider PRs though!
